// =========================================================== //

#include <json>

// =========================================================== //

#include <GlobalAPI/helpers/common>

// Auth
#include <GlobalAPI/helpers/auth/APIAuthStatus>

// Bans
#include <GlobalAPI/helpers/bans/APIBan>
#include <GlobalAPI/helpers/bans/APIBans>

// Jumpstats
#include <GlobalAPI/helpers/jumpstats/APIJumpstat>
#include <GlobalAPI/helpers/jumpstats/APIJumpstats>

// Maps
#include <GlobalAPI/helpers/maps/APIMap>
#include <GlobalAPI/helpers/maps/APIMaps>

// Modes
#include <GlobalAPI/helpers/modes/APIMode>
#include <GlobalAPI/helpers/modes/APIModes>

// Players
#include <GlobalAPI/helpers/players/APIPlayer>
#include <GlobalAPI/helpers/players/APIPlayers>

// Records
#include <GlobalAPI/helpers/records/APIRecord>
#include <GlobalAPI/helpers/records/APIRecords>

// Servers
#include <GlobalAPI/helpers/servers/APIServer>
#include <GlobalAPI/helpers/servers/APIServers>

// =========================================================== //